name: Build

on:
  push:
    branches:
    - master

jobs:
  ci:
    runs-on: windows-latest

    env:
      Actions_Allow_Unsecure_Commands: true
      Solution_Path: DavesSystemTuner.sln
      App_Project_Path: DavesSystemTuner\DavesSystemTuner.csproj

    steps:
      - name: Checkout
        uses: actions/checkout@v2
        with:
          fetch-depth: 0

      - name: Install .NET Core
        uses: actions/setup-dotnet@v3
        with:
          dotnet-version: '6.0.x'

      - name: Restore dependencies
        run: dotnet restore $env:App_Project_Path

      - name: Build application for release
        run: dotnet build $env:App_Project_Path --configuration Release --no-restore
