name: Build

on:
  push:
    branches:
    - master

jobs:
  ci:
    runs-on: windows-latest

    env:
      Actions_Allow_Unsecure_Commands: true
      App_Project_Path: DavesSystemTuner\DavesSystemTuner.csproj

    steps:
      - name: Checkout
        uses: actions/checkout@v3
        with:
          fetch-depth: 0

      - name: Install .NET Core
        uses: actions/setup-dotnet@v3

      - name: Restore Project Dependencies
        run: dotnet restore $env:App_Project_Path

      - name: Build Project for Release
        run: dotnet build $env:App_Project_Path --configuration Release --no-restore
